name: Run API Tests and Send Email Report

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 1:50 PM UTC (7:20 PM IST)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run API Test Runner
      run: python test_api_runner.py
